parent = iface.mainWindow()
mc = iface.mapCanvas()
lyr = mc.currentLayer()
crsSP = lyr.crs()
crsLL = QgsCoordinateReferenceSystem(4326)
xf = QgsCoordinateTransform(crsLL, crsSP, QgsProject.instance())
print(crsSP.description())
mu = crsSP.mapUnits()
print(mu, QgsUnitTypes.toString(mu))
sStr, bOk = QInputDialog.getText(parent, "Coordinates", "Enter coordinates as latitude, longitude: ", text="48.9, -122.4")
if bOk:
    lCoords = sStr.split(",")
    print(lCoords)
    lat = float(lCoords[0])
    lng = float(lCoords[1])
    pLL = QgsPointXY(lng, lat)
    print(pLL)
    pSP = xf.transform(pLL)
    print(pSP)
    gSP = QgsGeometry.fromPointXY(pSP)
    gBuffer = gSP .buffer(1, 8)
    print(gBuffer.boundingBox())
    lyr.selectByRect(gBuffer.boundingBox())
    if lyr.selectedFeatureCount()>0:
        mc.zoomToSelected()
    else:
        QMessageBox.information(parent, "Search Results", "No features selected")